### ISSUE TITLE
Typo in the repository's name!

### ISSUE THREAD

**Issue by chrispappas** [jessekorzan/expodal#3]
Expodal?

**Comment by jessekorzan** [comment]
Ha. After 10K+ page views... I was wondering when someone would notice. I misspelt the repo, doh. Too late now... but maybe I'll use the proper spelling for "Son of Explodal".

**Comment by impressivewebs** [comment]
FYI [according to this](https://github.com/blog/1508-repository-redirects-are-here) you should be able to rename it without any problems. Requests to the old name should redirect to the new one.

**Comment by jessekorzan** [comment]
@impressivewebs thx brah!

**Comment by nickbouton** [comment]
@jessekorzan You've got the wrong repo name linked on your AngelList profile too. 💩
