### ISSUE TITLE
Repo name spelling doesn't match.

### ISSUE THREAD

**Issue by josephdburdick** [jessekorzan/expodal#4]
Hey awesome idea but the repo address spelling  is incorrect.

**Comment by jessekorzan** [comment]
Good eye... You're the only other person after 40k+ page views to catch it. I have a repo with the proper spelling... Coming soon. Son of Explodal?

**Comment by jessekorzan** [comment]
Good eye... You're the only other person after 40k+ page views to catch it. I have a repo with the proper spelling... Coming soon. Son of Explodal?
